import Config

# Server state, in PostgreSQL (ADR 0028). `mix ecto.reset` is the whole reset.
#
# A local server has to be running — that is the cost ADR 0024 had bought and
# ADR 0028 spent. ADR 0028 spent it for a self-hosted core; ADR 0029 moved the
# core to the managed service, and the state stayed here. DATABASE_URL
# overrides every field below, which is how a developer points at a container
# instead.
#
# It cannot be inside the meal-plan folder, whatever anyone sets: a connection
# string names a host and a database, not a path in the sandbox mount.
# `url:` overrides the discrete fields, and Ecto rejects a nil one, so it is
# added only when DATABASE_URL is set rather than passed as nil.
dev_repo =
  [
    username: System.get_env("PGUSER") || "postgres",
    password: System.get_env("PGPASSWORD") || "postgres",
    hostname: System.get_env("PGHOST") || "127.0.0.1",
    port: String.to_integer(System.get_env("PGPORT") || "5432"),
    database: System.get_env("PGDATABASE") || "mealplan_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
  ]
  |> then(fn opts ->
    case System.get_env("DATABASE_URL") do
      nil -> opts
      "" -> opts
      url -> Keyword.put(opts, :url, url)
    end
  end)

config :mealplan, Mealplan.Repo, dev_repo

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :mealplan, MealplanWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "LMZ+PZVSQmTDCfik8UnYxUF3X+zFrcZcwbJcJU7huQBmo5In8Iy1aq9H+VszhF3T",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :mealplan, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
